// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2_4W_1DooErsfKmc9ZCO7cTAzkCHPzxg',
    appId: '1:154541946621:web:b2f22bf6ed0309fef67094',
    messagingSenderId: '154541946621',
    projectId: 'agrinfo-b745b',
    authDomain: 'agrinfo-b745b.firebaseapp.com',
    storageBucket: 'agrinfo-b745b.appspot.com',
    measurementId: 'G-6XEB1J7JQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3JKJJ8ILTvpACXdGKg6ZNh9b8JFdkwc',
    appId: '1:154541946621:android:45c820b0060854fdf67094',
    messagingSenderId: '154541946621',
    projectId: 'agrinfo-b745b',
    storageBucket: 'agrinfo-b745b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoKtQQTxZbNaaHFiy_Q-9-c6DBd2tCqBE',
    appId: '1:154541946621:ios:c1b5b2b7c3414c1bf67094',
    messagingSenderId: '154541946621',
    projectId: 'agrinfo-b745b',
    storageBucket: 'agrinfo-b745b.appspot.com',
    iosClientId: '154541946621-jg4e5cr3usnbqp2naftsd7r94q1pi2p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoKtQQTxZbNaaHFiy_Q-9-c6DBd2tCqBE',
    appId: '1:154541946621:ios:c1b5b2b7c3414c1bf67094',
    messagingSenderId: '154541946621',
    projectId: 'agrinfo-b745b',
    storageBucket: 'agrinfo-b745b.appspot.com',
    iosClientId: '154541946621-jg4e5cr3usnbqp2naftsd7r94q1pi2p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.agriInfo',
  );
}
